### PR TITLE
Better functions

### PR DESCRIPTION
**Pull request by hulien22**

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by hulien22** [comment]
not sure how that commit snuck into this pr...

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by hulien22** [comment]
Switching over to a prometheus-like function syntax, where we can do things like:
`sum(timeseries{name=~".*VALUE"}[count,1d])`
`(timeseries(description=~".*TEMP.*")[avg] - 32) * 5/9`
`max(timeseries{metadata.on="True")[count,5m]) - min(timeseries{metadata.on="True")[count,5m])`

**Comment by hulien22** [comment]
Still need to fix up tests and clean up a lot of code

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -it -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by hulien22** [comment]
All that's left is to fix up documentation :)

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -it -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -it -p 3000:3000 cognite/grafana-cdp-dev:pr-41`

**Comment by hulien22** [comment]
Something important to note: This pr does introduce a breaking change for functions as we will no longer accept for `function=` to be a property inside of `timeseries{ ... }`

**Pull request merged**
