### PR TITLE
adding /** @ngInject **/

### PR DESCRIPTION
**Pull request by hulien22**

### CODE REVIEW

**Comment by hulien22** [comment]
tfw you spend hours trying to fix a bug and it turns out to just be a one line comment in a file that hasn't been touched since the initial commit...

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -p 3000:3000 cognite/grafana-cdp-dev:pr-33`

**Comment by martincognite** [comment]
@hulien22 Did you intentionally close (and not merge) this one?

**Comment by hulien22** [comment]
oops

**Pull request merged**
