### PR TITLE
Fixing special functions so that we can still use normal max/min/avg …

### PR DESCRIPTION
**Pull request by hulien22**
…functions in combination

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -it -p 3000:3000 cognite/grafana-cdp-dev:pr-52`

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -it -p 3000:3000 cognite/grafana-cdp-dev:pr-52`

**Comment by martincognite** [comment]
I can make this fail by selecting a custom query, a root node with a high amount of time series (this one has 83) and using a custom function. `avg(timeseries{}[])` then gets a 504 :o.

**Comment by martincognite** [comment]
For another PR: pick a better label for the synthetic functions, we can at least use the function (`sum`, `avg` and such)

**Comment by cognite-cicd** [comment]
[pr-bot]
Run this build with `docker run --rm -it -p 3000:3000 cognite/grafana-cdp-dev:pr-52`

**Pull request merged**
